### ISSUE TITLE
Practica 1_Reporte de app de RA

### ISSUE THREAD

**Issue by Nancy2050** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-Nancy2050#2]
[Practica 1_Reporte de app de RA.pdf](https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-Nancy2050/files/8078165/Practica.1_Reporte.de.app.de.RA.pdf)

**Comment by Jaci14** [comment]
Cuenta con todos los puntos requeridos en la rubrica: describe objetivo de la practica, descripción, materiales etc., cuenta con una buena estructuración, es legible y entendible, cuenta con todas la ilustraciones (y descripciones de estas) requeridas. 

Pts alcanzados: 100
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
